"""Fetch and prepare a bounded data pilot. No text is generated by this program."""

import argparse
import collections
import csv
import datetime as dt
import gzip
import hashlib
import json
import math
from pathlib import Path
import re
import unicodedata
import urllib.request
import zipfile

ROOT = Path(__file__).resolve().parent
CONFIG = ROOT / "config/pilot.json"
RAW = ROOT / "data/raw"
OUT = ROOT / "data/pilot"
HUMAN_LABELS = {"human_translation"}
MACHINE_LABELS = {"machine_translation", "machine_assisted"}


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def normalized(text):
    # Only used for identity checks; the stored prose is not normalized.
    return " ".join(unicodedata.normalize("NFKC", text).casefold().split())


def text_hash(text):
    return sha256(text.encode("utf-8"))


def read_jsonl(path):
    with Path(path).open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def write_jsonl(path, rows):
    with Path(path).open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def write_json(path, value):
    Path(path).write_text(json.dumps(value, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def download(url, path, expected_sha):
    if path.exists():
        if sha256(path.read_bytes()) != expected_sha:
            raise ValueError(f"Checksum mismatch for {path}; existing file was not overwritten")
        return
    request = urllib.request.Request(url, headers={"User-Agent": "pretraining-datawork/0.1"})
    temporary = path.with_suffix(path.suffix + ".part")
    try:
        digest = hashlib.sha256()
        with urllib.request.urlopen(request, timeout=60) as response, temporary.open("wb") as handle:
            while block := response.read(1024 * 1024):
                digest.update(block)
                handle.write(block)
        if digest.hexdigest() != expected_sha:
            raise ValueError(f"Checksum mismatch from {url}; inspect upstream change before repinning")
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def fetch(config):
    RAW.mkdir(parents=True, exist_ok=True)
    for filename, spec in config["downloads"].items():
        download(spec["url"], RAW / filename, spec["sha256"])
        print(f"Verified {filename}", flush=True)
    # Keep a complete uncompressed row prefix, not a misleading truncated .gz.
    path = RAW / "hansard_prefix.jsonl"
    prefix_manifest = RAW / "hansard_prefix.manifest.json"
    if path.exists() and prefix_manifest.exists():
        previous = json.loads(prefix_manifest.read_text())
        if (previous["url"] != config["hansard"]["url"]
                or previous["rows"] != config["hansard_scan_rows"]
                or previous["sha256"] != sha256(path.read_bytes())):
            raise ValueError("Hansard prefix/config mismatch; use a new output location or remove the old prefix")
    else:
        temporary = path.with_suffix(".part")
        try:
            with urllib.request.urlopen(config["hansard"]["url"], timeout=60) as response:
                with gzip.GzipFile(fileobj=response) as stream, temporary.open("wb") as handle:
                    for _ in range(config["hansard_scan_rows"]):
                        line = stream.readline()
                        if not line:
                            raise ValueError("Hansard shard ended before requested prefix size")
                        json.loads(line)  # Validate each complete input row.
                        handle.write(line)
            temporary.replace(path)
            write_json(prefix_manifest, {
                **config["hansard"], "rows": config["hansard_scan_rows"],
                "sha256": sha256(path.read_bytes()),
                "hash_scope": "uncompressed complete-row prefix; not full remote shard",
            })
        finally:
            temporary.unlink(missing_ok=True)
    print(f"Verified Hansard prefix ({config['hansard_scan_rows']} rows)", flush=True)


def record(dataset, key, text, label, group, **kwargs):
    if not isinstance(text, str) or not text.strip():
        raise ValueError(f"Empty/non-text output: {dataset}/{key}")
    return {
        "id": f"{dataset}/{key}", "dataset": dataset, "text": text,
        "authorship": label, "document_group": f"{dataset}/{group}",
        "language": "en", "text_sha256": text_hash(text),
        "whitespace_words": len(text.split()),
        "publication_date": None, "text_version_date": None,
        "source_text": None, "source_language": None,
        "engine": None, "version_evidence": None,
        **kwargs,
    }


def hansard_decision(row, cutoff_year):
    metadata = row.get("metadata", {})
    if metadata.get("language") != "en":
        return "language_not_explicitly_english", None
    # Initial core is restricted to Westminster Commons/Lords records.
    if not re.fullmatch(r"uk-hansard-(commons|lords)-[a-z-]+", row.get("source", "")):
        return "source_requires_translation_provenance_review", None
    date_match = re.search(r"\d{4}-\d{2}-\d{2}", str(row.get("id", "")))
    if date_match is None:
        return "missing_document_date", None
    try:
        date = dt.date.fromisoformat(date_match.group())
        year = int(metadata["year"])
    except (ValueError, KeyError, TypeError):
        return "invalid_date_or_year", None
    if date.year != year:
        return "date_year_disagreement", None
    if year > cutoff_year:
        return "publication_after_cutoff", date.isoformat()
    if not isinstance(row.get("text"), str) or not row["text"].strip():
        return "empty_text", date.isoformat()
    return "retain_candidate", date.isoformat()


def load_hansard(config):
    records, rejected = [], []
    seen = set()
    for line, row in enumerate(read_jsonl(RAW / "hansard_prefix.jsonl"), 1):
        reason, date = hansard_decision(row, config["cutoff_year"])
        identity = (row.get("source"), row.get("id"))
        if reason == "retain_candidate" and identity in seen:
            reason = "duplicate_document_id"
        if reason != "retain_candidate":
            rejected.append({"dataset": "hansard", "id": row.get("id"), "input_line": line,
                             "reason": reason, "publication_date": date})
            continue
        seen.add(identity)
        records.append(record(
            "hansard", f"{row['source']}/{row['id']}", row["text"], "human_candidate", row["id"],
            publication_date=date, input_line=line, source=row["source"],
            metadata=row["metadata"], collected_date=row.get("added"),
            provenance_url=config["hansard"]["url"],
            license_status="Open Parliament Licence reported upstream",
            evidence="Official proceedings dated by document ID and metadata.year; authorship inferred",
            version_evidence="Publication date only; later corrections/version history not independently verified",
        ))
    return records, rejected


def strip_mqm_markup(text):
    # Remove only the annotation wrappers, retaining the annotated error text.
    return re.sub(r"</?v>", "", text)


def parse_wmt21(path, provenance_url):
    items = {}
    conflicts = {}
    with Path(path).open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        required = {"system", "doc", "seg_id", "source", "target"}
        if not required <= set(reader.fieldnames or []):
            raise ValueError("Unexpected WMT21 columns")
        for line, row in enumerate(reader, 2):
            system = row["system"]
            if system in {"ref.A", "ref.B"}:
                label = "human_translation"
            elif system.startswith("hyp."):
                label = "machine_translation"
            else:
                raise ValueError(f"Unreviewed WMT21 system label {system}")
            key = (row["doc"], row["seg_id"], system)
            text, source = strip_mqm_markup(row["target"]), strip_mqm_markup(row["source"])
            if key in items:
                if items[key]["text"] != text or items[key]["source_text"] != source:
                    conflicts[key] = {"dataset": "wmt21_zhen", "id": items[key]["id"],
                                      "reason": "conflicting_annotation_text", "first_input_line": items[key]["input_line"],
                                      "conflicting_input_line": line}
                items[key]["annotation_rows"] += 1
                continue
            items[key] = record(
                "wmt21_zhen", "/".join(key), text, label, row["doc"],
                source_text=source, source_language="zh", engine=system,
                segment_index=int(row["seg_id"]),
                provenance_url=provenance_url, input_line=line, annotation_rows=1,
                license_status="Repository Apache-2.0; underlying WMT/news text rights require separate review",
                evidence="Explicit WMT human reference / system output label; MQM scores do not determine authorship",
                version_evidence="WMT2021 benchmark translation; exact generation date not supplied",
            )
    return [value for key, value in items.items() if key not in conflicts], list(conflicts.values())


# ref-Google is HUMAN translation commissioned by Google, not Google Translate.
# Map by documented workflow, never by filename substring such as 'ref'.
COLLABORATIVE = {
    "refA": ("human_translation", "OrigHumanRef", "human", None),
    "ref-Google": ("human_translation", "HumanRef", "human", None),
    "ref-Google-edited": ("human_translation", "HumanRef+HumanPE", "human", "human"),
    "ref-Google-edited2": ("human_translation", "HumanRef+HumanPEx2", "human", "human_twice"),
    "ref-Google-llmrefine": ("machine_assisted", "HumanRef+LLMRefine", "human", "Gemini-1.0 Ultra"),
    "ref-best-wmt": ("machine_translation", "BestWMT", "Lan-BridgeMT", None),
    "ref-mid-wmt": ("machine_translation", "MidWMT", "ONLINE-G", None),
    "ref-best-wmt-edited": ("machine_assisted", "BestWMT+HumanPE", "Lan-BridgeMT", "human"),
    "ref-mid-wmt-edited": ("machine_assisted", "MidWMT+HumanPE", "ONLINE-G", "human"),
    "ref-best-wmt-llmrefine": ("machine_assisted", "BestWMT+LLMRefine", "Lan-BridgeMT", "Gemini-1.0 Ultra"),
    "ref-mid-wmt-llmrefine": ("machine_assisted", "MidWMT+LLMRefine", "ONLINE-G", "Gemini-1.0 Ultra"),
}


def load_collaborative(config):
    records = []
    with zipfile.ZipFile(RAW / "collaborative.zip") as archive:
        prefix = "wmt23_collaborative_collection_release/data/generaltest2023.zh-en."
        sources = archive.read(prefix + "src.zh").decode("utf-8").splitlines()
        metadata = archive.read("wmt23_collaborative_collection_release/data/zh-en.metadata").decode().splitlines()
        if len(metadata) != len(sources):
            raise ValueError("Collaborative metadata/source alignment mismatch")
        for name, (label, workflow, initial, postedit) in COLLABORATIVE.items():
            member = prefix + f"ref.{name}.en"
            targets = archive.read(member).decode("utf-8").splitlines()
            if len(targets) != len(sources):
                raise ValueError(f"Collaborative target alignment mismatch: {name}")
            for index, (source, text, meta) in enumerate(zip(sources, targets, metadata), 1):
                domain, doc = meta.split("\t", 1)
                records.append(record(
                    "collaborative_zhen", f"{index}/{name}", text, label, doc,
                    source_text=source, source_language="zh", engine=initial,
                    posteditor=postedit, workflow=workflow, domain=domain,
                    provenance_url=config["downloads"]["collaborative.zip"]["url"],
                    archive_member=member, input_line=index,
                    segment_index=index,
                    license_status="Download README has no explicit dataset license; review underlying WMT terms",
                    evidence="Workflow mapping from paper section 2.2 and released file names",
                    version_evidence="WMT2023 source set / 2024 study; exact translation dates unavailable",
                ))
    return records


def load_mwe(config):
    import openpyxl

    records = []
    workbook = openpyxl.load_workbook(RAW / "mwe.xlsx", read_only=True, data_only=True)
    try:
        for sheet in workbook:
            if sheet.title == "Analysis":
                continue
            # Each documented MWE sheet has 100 observations in rows 2..101.
            # Rows 103 onward are analysis labels/totals, not observations.
            rows = sheet.iter_rows(min_row=1, max_row=101, max_col=7, values_only=True)
            header = next(rows)
            expected = ("Source", "DEEPL", "Result", "GT", "Result 2", "CHATGPT", "Result 3")
            if header != expected:
                raise ValueError(f"Unexpected MWE columns on {sheet.title}: {header}")
            for rownum, values in enumerate(rows, 2):
                if not isinstance(values[0], str) or not values[0].strip():
                    raise ValueError(f"Missing MWE source at {sheet.title}/{rownum}")
                for col, engine in [(1, "DeepL Classic/NMT"), (3, "Google Translate"), (5, "GPT-4o")]:
                    score = values[col + 1]
                    if score is not None and score not in (0, 1):
                        raise ValueError(f"Invalid MWE annotation at {sheet.title}/{rownum}/{engine}")
                    records.append(record(
                        "mwe_es_en", f"{sheet.title}/{rownum}/{engine}", values[col],
                        "machine_translation", f"{sheet.title}/{rownum}",
                        source_text=values[0], source_language="es", engine=engine,
                        worksheet=sheet.title, input_row=rownum, idiom_correct=int(score) if score is not None else None,
                        segment_index=rownum,
                        provenance_url=config["downloads"]["mwe.xlsx"]["url"],
                        license_status="CC-BY-4.0 in Zenodo API metadata",
                        evidence="Explicit GT/DEEPL/CHATGPT columns; human evaluation is an idiom-quality annotation",
                        version_evidence="Published 2026-01-23; generation date/model snapshot unavailable",
                    ))
    finally:
        workbook.close()
    if len(records) != 1800:
        raise ValueError(f"Expected 600 source passages × 3 systems, found {len(records)} outputs")
    return records


class UnionFind:
    def __init__(self):
        self.parent = {}

    def find(self, item):
        self.parent.setdefault(item, item)
        if self.parent[item] != item:
            self.parent[item] = self.find(self.parent[item])
        return self.parent[item]

    def union(self, first, second):
        a, b = self.find(first), self.find(second)
        if a != b:
            # Stable canonical representative, independent of input order.
            self.parent[max(a, b)] = min(a, b)


def assign_splits(records):
    groups = UnionFind()
    identities, text_labels = {}, collections.defaultdict(set)
    ids = set()
    for row in records:
        if row["id"] in ids:
            raise ValueError(f"Duplicate record ID: {row['id']}")
        ids.add(row["id"])
        doc = row["document_group"]
        groups.find(doc)
        identities_for_row = [("target:en", normalized(row["text"]))]
        if row.get("source_text"):
            identities_for_row.append((f"source:{row['source_language']}", normalized(row["source_text"])))
        for kind, text in identities_for_row:
            identity = f"{kind}:{text_hash(text)}"
            if identity in identities:
                groups.union(doc, identities[identity])
            else:
                identities[identity] = doc
        if row["authorship"] in HUMAN_LABELS | MACHINE_LABELS:
            text_labels[normalized(row["text"])].add(0 if row["authorship"] in HUMAN_LABELS else 1)
    for row in records:
        group = groups.find(row["document_group"])
        row["split_group"] = group
        bucket = int(text_hash("pilot-v1:" + group)[:16], 16) % 100
        row["split"] = "train" if bucket < 80 else "validation" if bucket < 90 else "test"
        ambiguous = len(text_labels[normalized(row["text"])]) > 1
        row["ambiguous_text"] = ambiguous
        label = row["authorship"]
        row["binary_target"] = None if ambiguous else 0 if label in HUMAN_LABELS else 1 if label in MACHINE_LABELS else None


def verify_records(records):
    seen_ids, identities = set(), {}
    for row in records:
        if row["id"] in seen_ids:
            raise ValueError("Duplicate ID in prepared records")
        seen_ids.add(row["id"])
        if row["text_sha256"] != text_hash(row["text"]):
            raise ValueError(f"Text checksum changed: {row['id']}")
        keys = [("group", row["split_group"]), ("target", normalized(row["text"]))]
        if row.get("source_text"):
            keys.append((row["source_language"], normalized(row["source_text"])))
        for key in keys:
            if key in identities and identities[key] != row["split"]:
                raise ValueError(f"Split leakage for {row['id']}")
            identities[key] = row["split"]


def summarize(records):
    by_dataset = {}
    for name in sorted({r["dataset"] for r in records}):
        subset = [r for r in records if r["dataset"] == name]
        by_dataset[name] = {
            "records": len(subset), "whitespace_words": sum(r["whitespace_words"] for r in subset),
            "documents": len({r["document_group"] for r in subset}),
            "authorship": dict(collections.Counter(r["authorship"] for r in subset)),
            "engines": dict(collections.Counter(r["engine"] for r in subset)),
            "splits": dict(collections.Counter(r["split"] for r in subset)),
            "ambiguous_text_records": sum(r["ambiguous_text"] for r in subset),
        }
    return by_dataset


def binary_examples(records):
    """One representative per comparable text, retaining all equivalent record IDs."""
    by_text = collections.defaultdict(list)
    for row in records:
        if row["binary_target"] is not None:
            by_text[normalized(row["text"])].append(row)
    examples = []
    for equivalent in by_text.values():
        # Prefer original human or raw machine output over post-edit variants.
        selected = min(equivalent, key=lambda r: (r["authorship"] == "machine_assisted",
                                                  r.get("posteditor") is not None, r["id"]))
        examples.append({**selected, "equivalent_record_ids": sorted(r["id"] for r in equivalent)})
    return sorted(examples, key=lambda r: r["id"])


def translation_spans(records, tokenizer, min_tokens, max_tokens):
    """Build aligned contiguous spans, using common boundaries for all variants."""
    if not 0 < min_tokens <= max_tokens:
        raise ValueError("Require 0 < min_tokens <= max_tokens")
    documents = collections.defaultdict(lambda: collections.defaultdict(dict))
    for row in records:
        if row["authorship"] == "human_candidate":
            continue
        variant = row.get("workflow") or row["engine"]
        documents[row["document_group"]][row["segment_index"]][variant] = row
    spans, skipped = [], collections.Counter()
    for doc, segments in sorted(documents.items()):
        variants = sorted({v for segment in segments.values() for v in segment})
        current, previous = [], None
        def texts(block):
            return {v: "\n".join(segment[v]["text"] for _, segment in block) for v in variants}
        def emit(block):
            if not block:
                return
            joined = texts(block)
            counts = {v: len(tokenizer.encode(text, add_special_tokens=False).ids) for v, text in joined.items()}
            if min(counts.values()) < min_tokens:
                skipped["aligned_block_too_short"] += 1
                return
            source = "\n".join(segment[variants[0]]["source_text"] for _, segment in block)
            for v in variants:
                first = block[0][1][v]
                start, end = block[0][0], block[-1][0]
                spans.append({**first, "id": f"span/{doc}/{start}-{end}/{v}",
                              "text": joined[v], "text_sha256": text_hash(joined[v]),
                              "source_text": source, "token_count": counts[v],
                              "whitespace_words": len(joined[v].split()),
                              "document_group": first["split_group"],
                              "segment_record_ids": [segment[v]["id"] for _, segment in block],
                              "span_segment_range": [start, end], "span_join_separator": "newline"})
        for index, segment in sorted(segments.items()):
            complete = set(segment) == set(variants)
            sources_agree = complete and len({normalized(r["source_text"]) for r in segment.values()}) == 1
            if not sources_agree:
                emit(current); current, previous = [], None
                skipped["incomplete_or_conflicting_aligned_segment"] += 1
                continue
            if previous is not None and index != previous + 1:
                emit(current); current = []
            proposed = current + [(index, segment)]
            if max(len(tokenizer.encode(text, add_special_tokens=False).ids) for text in texts(proposed).values()) > max_tokens:
                emit(current); current = []
                proposed = [(index, segment)]
                if max(len(tokenizer.encode(text, add_special_tokens=False).ids) for text in texts(proposed).values()) > max_tokens:
                    skipped["single_segment_exceeds_maximum"] += 1
                    previous = None
                    continue
            current = proposed
            previous = index
        emit(current)
    assign_splits(spans)
    verify_records(spans)
    return spans, dict(skipped)


def build(config):
    # Offline building verifies that fetch inputs match the frozen configuration.
    for filename, spec in config["downloads"].items():
        if sha256((RAW / filename).read_bytes()) != spec["sha256"]:
            raise ValueError(f"Input checksum mismatch: {filename}")
    prefix_manifest = json.loads((RAW / "hansard_prefix.manifest.json").read_text())
    if (prefix_manifest["sha256"] != sha256((RAW / "hansard_prefix.jsonl").read_bytes())
            or prefix_manifest["url"] != config["hansard"]["url"]
            or prefix_manifest["rows"] != config["hansard_scan_rows"]):
        raise ValueError("Hansard prefix checksum/config mismatch")
    candidates, rejected = load_hansard(config)
    wmt21, annotation_rejections = parse_wmt21(RAW / "wmt21_zhen.tsv", config["downloads"]["wmt21_zhen.tsv"]["url"])
    rejected += annotation_rejections
    records = candidates + wmt21
    records += load_collaborative(config) + load_mwe(config)
    assign_splits(records)
    verify_records(records)
    records.sort(key=lambda r: r["id"])
    binary = binary_examples(records)
    OUT.mkdir(parents=True, exist_ok=True)
    write_jsonl(OUT / "records.jsonl", records)
    write_jsonl(OUT / "human_candidates.jsonl", [r for r in records if r["authorship"] == "human_candidate"])
    write_jsonl(OUT / "translation_examples.jsonl", [r for r in records if r["authorship"] != "human_candidate"])
    write_jsonl(OUT / "binary_examples.jsonl", binary)
    write_jsonl(OUT / "rejections.jsonl", rejected)
    write_jsonl(OUT / "review_queue.jsonl", [{
        "id": r["id"], "text_sha256": r["text_sha256"],
        "review_status": "unreviewed", "reviewer": None, "evidence_url": None,
        "human_authorship_evidence": None, "text_version_evidence": None,
    } for r in candidates])
    summary = {"datasets": summarize(records),
               "binary_examples": {"records": len(binary),
                                   "targets": dict(collections.Counter(str(r["binary_target"]) for r in binary)),
                                   "splits": dict(collections.Counter(r["split"] for r in binary))},
               "rejections": dict(collections.Counter(r["reason"] for r in rejected)),
               "checks": {"unique_ids": True, "text_hashes_match": True, "exact_text_and_document_split_leakage": False},
               "limitations": ["Hansard is a convenience prefix, not a random audit",
                               "Hansard publication dates do not prove captured revision dates or human authorship",
                               "Near duplicates, shared boilerplate and publisher-level overlap are not screened",
                               "Word counts use whitespace splitting, not a model tokenizer",
                               "These splits do not test held-out engines, years or languages"]}
    write_json(OUT / "summary.json", summary)
    inputs = [{"file": str(p.relative_to(ROOT)), "sha256": sha256(p.read_bytes()), "bytes": p.stat().st_size}
              for p in sorted(RAW.iterdir()) if p.is_file() and not p.name.endswith(".part")]
    outputs = [{"file": str(p.relative_to(ROOT)), "sha256": sha256(p.read_bytes()), "bytes": p.stat().st_size}
               for p in sorted(OUT.iterdir()) if p.name in {"records.jsonl", "human_candidates.jsonl", "translation_examples.jsonl", "binary_examples.jsonl", "rejections.jsonl", "review_queue.jsonl", "summary.json"}]
    write_json(OUT / "manifest.json", {"built_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
               "config_sha256": sha256(CONFIG.read_bytes()), "script_sha256": sha256(Path(__file__).read_bytes()),
               "config": config, "inputs": inputs, "outputs": outputs})
    print(json.dumps(summary, indent=2))


def wilson(successes, total):
    if total == 0:
        return None
    z = 1.959963984540054
    p = successes / total
    denom = 1 + z * z / total
    center = (p + z * z / (2 * total)) / denom
    margin = z * math.sqrt(p * (1 - p) / total + z * z / (4 * total * total)) / denom
    return [max(0, center - margin), min(1, center + margin)]


def evaluate(records, scores, threshold, split):
    if not math.isfinite(threshold) or not 0 <= threshold <= 1:
        raise ValueError("Threshold must be in [0, 1]")
    by_id = {r["id"]: r for r in records}
    prepared = {}
    for score in scores:
        key, probability = score["id"], score["score"]
        if key not in by_id or key in prepared:
            raise ValueError(f"Unknown or duplicate score ID: {key}")
        if isinstance(probability, bool) or not isinstance(probability, (int, float)) or not math.isfinite(probability) or not 0 <= probability <= 1:
            raise ValueError(f"Invalid score for {key}")
        prepared[key] = probability
    groups = collections.defaultdict(list)
    missing = 0
    for row in records:
        if row["split"] != split or row["binary_target"] is None:
            continue
        if row["id"] not in prepared:
            missing += 1
            continue
        predicted = int(prepared[row["id"]] >= threshold)
        word_count = row["whitespace_words"]
        length = "under_50_words" if word_count < 50 else "50_to_199_words" if word_count < 200 else "200_plus_words"
        for group in {"all", f"dataset:{row['dataset']}", f"origin:{row['authorship']}", f"engine:{row['engine']}",
                      f"length:{length}", f"domain:{row.get('domain', 'unspecified')}", f"source_language:{row['source_language']}"}:
            groups[group].append((row["binary_target"], predicted, row["whitespace_words"]))
    output = {}
    for name, rows in sorted(groups.items()):
        counts = collections.Counter((truth, prediction) for truth, prediction, _ in rows)
        negatives = counts[0, 0] + counts[0, 1]
        positives = counts[1, 0] + counts[1, 1]
        human_words = sum(words for truth, _, words in rows if truth == 0)
        machine_words = sum(words for truth, _, words in rows if truth == 1)
        output[name] = {
            "scored_records": len(rows), "human_false_positive_rate": counts[0, 1] / negatives if negatives else None,
            "human_fpr_wilson95": wilson(counts[0, 1], negatives),
            "machine_recall": counts[1, 1] / positives if positives else None,
            "machine_recall_wilson95": wilson(counts[1, 1], positives),
            "human_word_weighted_fpr": sum(words for truth, pred, words in rows if truth == 0 and pred == 1) / human_words if human_words else None,
            "machine_word_weighted_recall": sum(words for truth, pred, words in rows if truth == 1 and pred == 1) / machine_words if machine_words else None,
            "confusion": {"tn": counts[0, 0], "fp": counts[0, 1], "fn": counts[1, 0], "tp": counts[1, 1]},
        }
    return {"split": split, "threshold": threshold, "missing_eligible_scores": missing,
            "metrics": output, "interval_note": "Wilson intervals assume independent records; use document-cluster bootstrap for final claims",
            "scope": "Translation authorship only. Human candidates/ambiguous texts excluded. Does not estimate corpus contamination."}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("fetch", help="Fetch/verify ~15 MB of translation data plus a bounded Hansard prefix")
    sub.add_parser("build", help="Build JSONL records offline, preserving provenance and authorship labels")
    sub.add_parser("verify", help="Verify prepared hashes, IDs and split leakage")
    span_parser = sub.add_parser("spans", help="Build longer aligned translation passages with shared segment boundaries")
    span_parser.add_argument("--tokenizer-json", type=Path, required=True)
    span_parser.add_argument("--min-tokens", type=int, default=512)
    span_parser.add_argument("--max-tokens", type=int, default=4096)
    scoring = sub.add_parser("evaluate", help="Evaluate external machine-authorship scores")
    scoring.add_argument("--scores", type=Path, required=True, help="JSONL with id and score (higher = more machine-like)")
    scoring.add_argument("--threshold", type=float, required=True)
    scoring.add_argument("--split", choices=["validation", "test"], default="test")
    scoring.add_argument("--examples", type=Path, default=OUT / "binary_examples.jsonl")
    args = parser.parse_args()
    config = json.loads(CONFIG.read_text())
    if args.command == "fetch":
        fetch(config)
    elif args.command == "build":
        build(config)
    elif args.command == "verify":
        records = read_jsonl(OUT / "records.jsonl")
        verify_records(records)
        binary = read_jsonl(OUT / "binary_examples.jsonl")
        verify_records(binary)
        if len({normalized(r["text"]) for r in binary}) != len(binary):
            raise ValueError("Duplicate normalized text in binary examples")
        manifest = json.loads((OUT / "manifest.json").read_text())
        for artifact in manifest["outputs"]:
            if sha256((ROOT / artifact["file"]).read_bytes()) != artifact["sha256"]:
                raise ValueError(f"Output checksum mismatch: {artifact['file']}")
        print(f"Verified {len(records)} records, text hashes, manifest outputs and split isolation")
    elif args.command == "spans":
        from tokenizers import Tokenizer
        tokenizer = Tokenizer.from_file(str(args.tokenizer_json))
        tokenizer.no_padding(); tokenizer.no_truncation()
        spans, skipped = translation_spans(read_jsonl(OUT / "records.jsonl"), tokenizer, args.min_tokens, args.max_tokens)
        binary = binary_examples(spans)
        write_jsonl(OUT / "translation_spans.jsonl", spans)
        write_jsonl(OUT / "binary_spans.jsonl", binary)
        summary = {"min_tokens": args.min_tokens, "max_tokens": args.max_tokens, "records": len(spans),
                   "binary_records": len(binary), "skipped_blocks_or_segments": skipped,
                   "tokenizer_sha256": sha256(args.tokenizer_json.read_bytes()),
                   "source_records_sha256": sha256((OUT / "records.jsonl").read_bytes()),
                   "script_sha256": sha256(Path(__file__).read_bytes()),
                   "outputs": {name: sha256((OUT / name).read_bytes()) for name in ["translation_spans.jsonl", "binary_spans.jsonl"]},
                   "limitations": ["Newlines join only contiguous source segments within a document",
                                   "All variants of a block share boundaries; short/incomplete blocks excluded",
                                   "Span splits are for this export; do not mix with sentence export without regrouping"]}
        write_json(OUT / "spans.manifest.json", summary)
        print(json.dumps(summary, indent=2))
    else:
        report = evaluate(read_jsonl(args.examples), read_jsonl(args.scores), args.threshold, args.split)
        print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
